name: GitHub Actions Text

on:
  schedule:
    - cron: "*/5 * * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install mailjetAPI
        run: pip install mailjet_rest
      - name: execute py script # run the run.py to get the latest data
        run: |
          python GitHubActionsTest.py
      
